---
abstract: 'Verify the consistency of license and copyright information'
author:
  - 'Nicholas Bamber <nicholas@periapt.co.uk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Copyright
provides:
  Test::Copyright:
    file: lib/Test/Copyright.pm
    version: 0.0_1
requires:
  CPAN::Meta: 0
  Email::Address: 0
  Lingua::EN::NameParse: 0
  Perl6::Slurp: 0
  Readonly: 0
  Software::LicenseUtils: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/periapt/Test-Copyright/tree
version: 0.0_1
